version: "3.8"

services:
  db:
    image: mongo
    restart: always
    container_name: db
    volumes:
      - code_data:/data/db
    ports:
      - 27017:27017
  
  backend:
    build: ./src/flask
    container_name: backend
    stop_signal: SIGINT
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://db:27017/CodeIndex
      MONGO_OPLOG_URL: mongodb://db:27017/local
      ROOT_URL: http://localhost:3000
      PORT: 3000
    depends_on:
      - db
    ports:
      - 3000:3000
    command: gunicorn -w 1 -b 0.0.0.0:3000  wsgi:app #also change the CMD in the flask docker file

  web:
    image: nginx
    container_name: web
    restart: unless-stopped
    environment:
      - FLASK_SERVER_ADDR=backend:3000
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    volumes:
      - ./src/nginx/nginx.conf:/tmp/nginx.conf
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend



volumes:
  code_data: