version: "3.8"

services:
  db:
    image: mongo
    restart: always
    container_name: db
    volumes:
      - code_data:/data/db
    ports:
      - 27017:27017
  web:
    build: ./src
    container_name: web
    stop_signal: SIGINT
    environment:
      MONGO_URL: mongodb://db:27017/CodeIndex
      MONGO_OPLOG_URL: mongodb://db:27017/local
      ROOT_URL: http://localhost:3000
      PORT: 3000
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  code_data: